### ISSUE TITLE
Slider is kept showing even after closing the filter

### ISSUE THREAD

**Issue by Algeneralo** [dcasia/nova-slider-filter#1]
I am facing an issue with the slider, the 2 dots are kept showing when I closed the filter 
Ex:
![image](https://user-images.githubusercontent.com/32073999/107991765-54c19280-6fe8-11eb-84c9-51d06fbb6cfe.png)
I'm using the last nova version: 3.17

**Comment by Algeneralo** [comment]
@milewski

**Comment by Algeneralo** [comment]
@milewski any updates regarding this issue?

**Comment by milewski** [comment]
@Algeneralo I don't have time right now to take a closer look at this issue, I think it might be solvable by triggering an input.blur() manually whenever a `click outside` is detected..  if you are able to submit a PR for this, would be more than happy to merge.

**Comment by Algeneralo** [comment]
@milewski 
I tried to, but there was an issue when I tried to compile the files again, something related to Sass loader.
Any idea?

**Comment by milewski** [comment]
Can you show me what's the error? perhaps you just need to remove node_modules and do `npm install` again?

**Comment by milewski** [comment]
No longer an issue on the latest version which now supports nova 4
