### ISSUE TITLE
RTL issue for slider 

### ISSUE THREAD

**Issue by Algeneralo** [dcasia/nova-slider-filter#2]
Since I'm using an RTL version of nova, the slider appears to be wronged as the following screen 
![image](https://user-images.githubusercontent.com/32073999/107992277-6c4d4b00-6fe9-11eb-818d-f3015a41eb50.png)
How can I customize it?

**Comment by milewski** [comment]
Sorry I'm not familiar with RTL, perhaps this can be solved by applying a CSS rule on the slider?

**Comment by Algeneralo** [comment]
Yeah, this could be fixed by that, but how can I do it?
or you should do it from the library itself?

**Comment by milewski** [comment]
You can create a nova theme that overrides some CSS https://nova.laravel.com/docs/3.0/customization/themes.html

**Comment by Algeneralo** [comment]
Thanks
